# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '仿淘宝' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 仿淘宝
pod 'Masonry'
pod 'MGSwipeTableCell'
pod 'SDWebImage'

  target '仿淘宝Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '仿淘宝UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
